import type { Metadata } from "next";
import { Jersey_15, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast"
import { QueryProvider } from "@/components/providers/QueryProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const jersey = Jersey_15({
  variable: "--font-jersey-next",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        jersey.className,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
      <Toaster />
    </html>
  );
}
