import type { Metadata } from "next";
import { Jersey_15 } from "next/font/google";
import "./globals.css";

const jersey = Jersey_15({
  variable: "--font-jersey-next",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${jersey.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
